INSERT INTO public.products (name, description, category, subcategory, gender, price, tags, sizes, colors, stock, image_url, try_on_enabled) VALUES
('Men''s Leather Jacket', 'Premium tan leather jacket with fur lining and military-style buttons. Warm and stylish for winter.', 'Jackets', 'Men > Jackets', 'Men', 3499, ARRAY['leather', 'winter', 'premium'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Tan', 'Brown', 'Black'], 30, '/images/jacket.png', true),
('Women''s Red Wool Coat', 'Elegant double-breasted wool coat with scallop trim detail. Perfect for formal occasions.', 'Jackets', 'Women > Jackets', 'Women', 4299, ARRAY['wool', 'formal', 'winter', 'elegant'], ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Red', 'Black', 'Navy'], 25, '/images/coat12.png', true),
('Bohemian Pattern Sweater', 'Hand-knitted bohemian sweater with traditional snowflake and zigzag patterns in turquoise and purple.', 'Tops', 'Unisex > Tops', 'Unisex', 1899, ARRAY['bohemian', 'knitted', 'winter', 'pattern'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Multicolor'], 40, '/images/sweater.png', true),
('Men''s Classic Red Shirt', 'Short-sleeve button-down shirt in rich burgundy red. Lightweight cotton for everyday comfort.', 'Shirts', 'Men > Shirts', 'Men', 1299, ARRAY['casual', 'cotton', 'summer'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Burgundy', 'Navy', 'White'], 60, '/images/tshirt.png', true),
('Navy Crewneck Sweatshirt', 'Classic navy blue crewneck sweatshirt. Soft fleece interior for maximum comfort.', 'Hoodies', 'Unisex > Hoodies', 'Unisex', 999, ARRAY['casual', 'basics', 'comfort'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Navy', 'Black', 'Grey'], 80, '/images/hooodie3.png', true),
('Ruffle Hem Mock Neck Dress', 'Navy ribbed mock-neck dress with checkered ruffle hem detail. Chic and modern.', 'Dresses', 'Women > Dresses', 'Women', 1599, ARRAY['elegant', 'modern', 'layered'], ARRAY['XS', 'S', 'M', 'L'], ARRAY['Navy', 'Black'], 35, '/images/dress7.png', true),
('Olive Oversized Shirt', 'Relaxed-fit olive green button-down with raw fringe hem. Military-inspired casual style.', 'Shirts', 'Women > Shirts', 'Women', 1199, ARRAY['oversized', 'casual', 'military'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Olive', 'Khaki', 'Black'], 45, '/images/dress6.png', true),
('Hot Pink Sports T-Shirt', 'Vibrant hot pink raglan-sleeve athletic tee. Moisture-wicking fabric for active wear.', 'T-Shirts', 'Unisex > T-Shirts', 'Unisex', 699, ARRAY['sports', 'active', 'bright'], ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['Hot Pink', 'Electric Blue', 'Lime'], 100, '/images/t_shirt.png', true),
('Men''s Grey Formal Shirt', 'Fine-check grey formal shirt with chest pocket. Ideal for office and smart-casual looks.', 'Shirts', 'Men > Shirts', 'Men', 1499, ARRAY['formal', 'office', 'smart'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Grey', 'Light Blue', 'White'], 50, '/images/shirt1.png', true),
('Peacock Embroidered Gown', 'Stunning strapless navy gown with peacock feather embroidery in gold and teal sequins. Perfect for galas.', 'Dresses', 'Women > Dresses', 'Women', 7999, ARRAY['party wear', 'gala', 'embroidered', 'luxury'], ARRAY['XS', 'S', 'M', 'L'], ARRAY['Navy', 'Black'], 15, '/images/dress_4.png', true);