INSERT INTO public.products (name, description, category, subcategory, gender, price, tags, sizes, colors, stock, image_url, try_on_enabled, rating, review_count) VALUES
('Men''s Classic Denim Jacket', 'Vintage wash denim jacket with rugged detailing and copper buttons.', 'Jackets', 'Men > Jackets', 'Men', 2499, ARRAY['denim','casual','rugged'], ARRAY['S','M','L','XL','XXL'], ARRAY['Dark Blue'], 30, '/images/jean-2.png', true, 4.5, 38),
('Purple Ruffle Ball Gown', 'Stunning purple organza ball gown with crystal embellishments and layered ruffles.', 'Dresses', 'Women > Dresses', 'Women', 8999, ARRAY['party','formal','gown','purple'], ARRAY['S','M','L','XL'], ARRAY['Purple'], 8, '/images/dress3-2.png', true, 4.9, 15),
('Navy Blue Slim Fit Blazer', 'Tailored slim-fit blazer in navy blue with striped lining. Perfect for formal events.', 'Blazers', 'Men > Blazers', 'Men', 3999, ARRAY['formal','blazer','slim fit'], ARRAY['S','M','L','XL'], ARRAY['Navy Blue'], 22, '/images/coat-2.png', true, 4.6, 29),
('Black Classic Hoodie', 'Comfortable pullover hoodie in solid black with kangaroo pocket and drawstring hood.', 'Hoodies', 'Unisex > Hoodies', 'Unisex', 1299, ARRAY['casual','streetwear','hoodie'], ARRAY['S','M','L','XL','XXL'], ARRAY['Black'], 55, '/images/hoodie-2.png', true, 4.4, 62),
('Striped Belted Blouse', 'Navy, red and white striped blouse with mock neck and waist tie belt.', 'Tops', 'Women > Tops', 'Women', 1199, ARRAY['striped','casual','chic'], ARRAY['XS','S','M','L'], ARRAY['Navy Stripe'], 35, '/images/dress_2-2.png', true, 4.3, 21),
('Floral Asymmetric Wrap Dress', 'White botanical print dress with green sash belt and asymmetric hemline.', 'Dresses', 'Women > Dresses', 'Women', 3499, ARRAY['floral','wrap','elegant'], ARRAY['S','M','L','XL'], ARRAY['White Floral'], 18, '/images/dress-2.png', true, 4.7, 33),
('Light Blue Peplum Blouse', 'Soft light blue peplum blouse with bow-tie bell sleeves. Elegant and airy.', 'Tops', 'Women > Tops', 'Women', 899, ARRAY['peplum','blouse','elegant'], ARRAY['XS','S','M','L'], ARRAY['Light Blue'], 42, '/images/girls_shirt-2.png', true, 4.2, 27),
('Women''s Light Wash Denim Jacket', 'Classic cropped denim jacket in light wash with rose gold buttons.', 'Jackets', 'Women > Jackets', 'Women', 1999, ARRAY['denim','casual','cropped'], ARRAY['XS','S','M','L','XL'], ARRAY['Light Blue'], 28, '/images/denim_girl-2.png', true, 4.5, 44),
('Purple Pleated Midi Dress', 'Elegant scoop-neck midi dress with pleated skirt in deep purple.', 'Dresses', 'Women > Dresses', 'Women', 1599, ARRAY['pleated','midi','elegant'], ARRAY['S','M','L','XL'], ARRAY['Deep Purple'], 32, '/images/gown-2.png', true, 4.4, 19),
('Men''s Classic White Shirt', 'Crisp white button-down shirt in premium cotton. A wardrobe essential.', 'Shirts', 'Men > Shirts', 'Men', 1299, ARRAY['formal','classic','white'], ARRAY['S','M','L','XL','XXL'], ARRAY['White'], 50, '/images/shirt-2.png', true, 4.6, 55);